version: '3'
services:
  app:
    container_name: app_node
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - db
    depends_on: 
      - db

  db:
    # build: ./db
    image: mysql
    container_name: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: server